volumes:
  mydbvol:

networks:
  mynet:

services:
  northwind-db:
    image: stackupiss/northwind-db:v1
    volumes:
      - mydbvol:/var/lib/mysql
    networks:
      - mynet

  northwind-app:
    image: stackupiss/northwind-app:v1
    networks:
      - mynet
    ports:
      - 8080-9000:3000
    environment:
      - DB_HOST=northwind-db
