---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: bggdb-configmap
  namespace: bggns  
  labels:
    name: bggdb-configmap
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-service.bggns.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata: 
  name: bggdb-secret
  namespace: bggns  
  labels:
    name: bggdb-secret
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: bggns
  name: bggapp-deployment
  labels:
    name: bggapp-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: bggapp-pod
  strategy:
    rollingUpdate:
      maxSurge : 1
      maxUnavailable: 0
  template:   
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: bggdb-configmap
        env:
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bggdb-secret
              key: BGG_DB_PASSWORD
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata: 
  namespace: bggns
  name: bggapp-service
  labels:
    name: bggapp-service
spec:
  type: LoadBalancer
  selector:
    name: bggapp-pod
  ports:
  - port: 8080
    targetPort: 3000