---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bgg-hpa-1
  labels:
    name: bgg-hpa-1
spec: 
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: bggapp-deployment-v1
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 10
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bgg-hpa-2
  labels:
    name: bgg-hpa-2
spec: 
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: bggapp-deployment-v2
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 70       